# Generated by Django 2.2 on 2020-05-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20200530_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='save_id',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='编辑历史ID'),
        ),
    ]
