# Generated by Django 2.2 on 2020-06-02 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_articlepost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialmanager',
            name='special',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mymanager', to='article.Special', verbose_name='专题'),
        ),
    ]
