# Generated by Django 2.2 on 2020-06-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_article_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pub_status',
            field=models.BooleanField(default=False, verbose_name='发布状态'),
        ),
    ]
