# Generated by Django 2.2 on 2020-06-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_remove_article_pub_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='special',
            name='isCheck',
            field=models.BooleanField(default=True, verbose_name='是否审核'),
        ),
        migrations.AddField(
            model_name='special',
            name='isContribute',
            field=models.BooleanField(default=True, verbose_name='是否投稿'),
        ),
    ]
